### ISSUE TITLE
Missing axios dependency

### ISSUE THREAD

**Issue by florianrusch** [fapspirit/axios-opentracing#2]
Is this package still alive? If it is so, I would recommend to add `axios` as dependency of this package into the `package.json`.

**Comment by fapspirit** [comment]
Hello! Yes, this package is still alive!
Could you explain why `axios` should be in `dependencies` instead of `peerDependencies`?

**Comment by florianrusch** [comment]
@fapspirit ah sorry. yes, you are right. I didn't saw this in the package.json 🙈
